package pe.edu.unsch.entities;
// Generated 05/07/2019 03:19:52 PM by Hibernate Tools 4.3.2-SNAPSHOT


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Semestreacademico generated by hbm2java
 */
@Entity
@Table(name="semestreacademico"
    ,catalog="cargabd"
)
public class Semestreacademico  implements java.io.Serializable {


     private Long idsemestre;
     private Calendario calendario;
     private Docente docente;
     private String anho;
     private String ciclo;
     private String descripcion;

    public Semestreacademico() {
    }

    public Semestreacademico(Calendario calendario, Docente docente, String anho, String ciclo, String descripcion) {
       this.calendario = calendario;
       this.docente = docente;
       this.anho = anho;
       this.ciclo = ciclo;
       this.descripcion = descripcion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idsemestre", unique=true, nullable=false)
    public Long getIdsemestre() {
        return this.idsemestre;
    }
    
    public void setIdsemestre(Long idsemestre) {
        this.idsemestre = idsemestre;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcalendario", nullable=false)
    public Calendario getCalendario() {
        return this.calendario;
    }
    
    public void setCalendario(Calendario calendario) {
        this.calendario = calendario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="iddocente", nullable=false)
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }

    
    @Column(name="anho", nullable=false, length=4)
    public String getAnho() {
        return this.anho;
    }
    
    public void setAnho(String anho) {
        this.anho = anho;
    }

    
    @Column(name="ciclo", nullable=false, length=2)
    public String getCiclo() {
        return this.ciclo;
    }
    
    public void setCiclo(String ciclo) {
        this.ciclo = ciclo;
    }

    
    @Column(name="descripcion", nullable=false)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


