package pe.edu.unsch.entities;
// Generated 05/07/2019 03:19:52 PM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="cargabd"
)
public class Usuario  implements java.io.Serializable {


     private Long idusuario;
     private String usuario;
     private String password;
     private Set<Docente> docentes = new HashSet<Docente>(0);

    public Usuario() {
    }

	
    public Usuario(String usuario, String password) {
        this.usuario = usuario;
        this.password = password;
    }
    public Usuario(String usuario, String password, Set<Docente> docentes) {
       this.usuario = usuario;
       this.password = password;
       this.docentes = docentes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idusuario", unique=true, nullable=false)
    public Long getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(Long idusuario) {
        this.idusuario = idusuario;
    }

    
    @Column(name="usuario", nullable=false, length=50)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="password", nullable=false, length=50)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<Docente> getDocentes() {
        return this.docentes;
    }
    
    public void setDocentes(Set<Docente> docentes) {
        this.docentes = docentes;
    }




}


